// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9aVWKdmRJJSYnuf9l56-f9h-smcgo3mQ',
    appId: '1:278523898637:web:776e105e58d6cbdbbb1e44',
    messagingSenderId: '278523898637',
    projectId: 'neuroplay-4b82d',
    authDomain: 'neuroplay-4b82d.firebaseapp.com',
    storageBucket: 'neuroplay-4b82d.firebasestorage.app',
    measurementId: 'G-GNGMTW4B9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuqOVtgwfOK8qzWteI7DY6JttyDw1qarM',
    appId: '1:278523898637:android:aaf045323c44d420bb1e44',
    messagingSenderId: '278523898637',
    projectId: 'neuroplay-4b82d',
    storageBucket: 'neuroplay-4b82d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKHP3i9GAWUetAPJ44k_OGuUQX_VfQ1fw',
    appId: '1:278523898637:ios:d62a17030b1e0cd4bb1e44',
    messagingSenderId: '278523898637',
    projectId: 'neuroplay-4b82d',
    storageBucket: 'neuroplay-4b82d.firebasestorage.app',
    androidClientId: '278523898637-40mlgnd6le88vd1vhr5u79bplqsv16vs.apps.googleusercontent.com',
    iosClientId: '278523898637-ek122uk1dslb8kie90tmfnv5do5v9i0c.apps.googleusercontent.com',
    iosBundleId: 'com.example.fft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKHP3i9GAWUetAPJ44k_OGuUQX_VfQ1fw',
    appId: '1:278523898637:ios:d62a17030b1e0cd4bb1e44',
    messagingSenderId: '278523898637',
    projectId: 'neuroplay-4b82d',
    storageBucket: 'neuroplay-4b82d.firebasestorage.app',
    androidClientId: '278523898637-40mlgnd6le88vd1vhr5u79bplqsv16vs.apps.googleusercontent.com',
    iosClientId: '278523898637-ek122uk1dslb8kie90tmfnv5do5v9i0c.apps.googleusercontent.com',
    iosBundleId: 'com.example.fft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9aVWKdmRJJSYnuf9l56-f9h-smcgo3mQ',
    appId: '1:278523898637:web:7c5d0f699932e177bb1e44',
    messagingSenderId: '278523898637',
    projectId: 'neuroplay-4b82d',
    authDomain: 'neuroplay-4b82d.firebaseapp.com',
    storageBucket: 'neuroplay-4b82d.firebasestorage.app',
    measurementId: 'G-918PZNPMB4',
  );
}
